---
- name: Install nginx
  hosts: all
  become: yes
  tasks:  
  - name: Install nginx
    apt: name=nginx state=installed
	
  - name: Start and enable nginx
    service: name=nginx state=started enabled=yes